### PR TITLE
fix: add -w option to base64 command in circleci activation process

### PR DESCRIPTION
**Pull request by alexjorgef**
#### Changes

- In order to disable line wrapping, add `-w 0` option to the base64 command in the CircleCI activation process

#### Checklist

- [X] Read the contribution [guide](../blob/main/CONTRIBUTING.md) and accept the
      [code](../blob/main/CODE_OF_CONDUCT.md) of conduct
- [X] Readme (updated or not needed)
- [X] Tests (added, updated or not needed)

### CODE REVIEW

**Comment by webbertakken** [comment]
I'm not sure why this would be needed, seems to work perfectly well without it.

Could you please provide additional context about the use cases where it does in fact not work?

**Comment by alexjorgef** [comment]
> I'm not sure why this would be needed, seems to work perfectly well without it.
> 
> Could you please provide additional context about the use cases where it does in fact not work?

Open a thread on Discord `#help` channel (https://discord.com/channels/710946343828455455/1054825834512384042) and seems to be the missing option that causes the issue.

But also, could be that I'm using an IL2CPP platform when the game license has on the Mono platform, I will test this again without that option. Thank for your feedback @webbertakken

**Comment by webbertakken** [comment]
Sounds good. If this is indeed needed we'd be happy to merge it.

**Comment by alexjorgef** [comment]
@webbertakken I test again,

failed at the "Prepare the environment" step `❯ cat Unity_v2021.x.ulf | base64 > UNITY_ENCODED_LICENSE` (with and without the final newline):

```shell
Detected OS: Linux.
base64: invalid input
Failed to find the serial or parse it from the Unity license.
Please try again or open an issue.

Exited with code exit status 1
```

Pass with `❯ cat Unity_v2021.x.ulf | base64 -w 0 > UNITY_ENCODED_LICENSE` (output is a one-line string without any newline):

```shell
Detected OS: Linux.
+++ mkdir -p /root/.cache/unity3d
+++ mkdir -p /root/.local/share/unity3d/Unity/
+++ set +x
Writing '$UNITY_LICENSE' to license file /root/.local/share/unity3d/Unity/Unity_lic.ulf
```

**Comment by webbertakken** [comment]
Cool. Feel free to reopen.

**Comment by alexjorgef** [comment]
> Cool. Feel free to reopen.

@webbertakken when we don't use `-w 0`, binary encoding to multi-lines, and then due to some systems using different `base64` binaries, which could be caused by the line separator which defaults to Windows ("\r\n") and Linux ("\n") systems.

**Pull request closed without merging**
