### PR TITLE
Avoid needing escapes in bash

### PR DESCRIPTION
**Pull request by Bengt**
#### Changes

- Use single quotes to make this call safe for passwords generated by Google Chrome's password generator

#### Checklist

- [x] Read the contribution [guide](../blob/main/CONTRIBUTING.md) and accept the [code](../blob/main/CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Review by webbertakken — CHANGES_REQUESTED** [review]
I'm not sure I'm misunderstanding or not, but we don't ever recommend hardcoding any passwords in CI workflows. Turning variable names into hardcoded string also breaks coherence from previous steps.

**Comment by Bengt** [comment]
Hi, @webbertakken! Yes, the passwords were expected to be set in the environment, but this command is run in the BASH shell of the started Docker container. Hence, there are no environment variables set and this fails as-is. By inserting the username and password into the command and escaping them using single quotes, they can be accessed without environment variables.

**Comment by webbertakken** [comment]
Actually the command right above it explains how to pass the environment variable.

image

I believe the current explanation works as expected.

**Comment by Bengt** [comment]
Ahhhh, true. That would have worked, but I overlooked it. Nevermind, then.

**Pull request closed without merging**
