### PR TITLE
Fix discord page

### PR DESCRIPTION
**Pull request by webbertakken**
...related to next issue 8113

#### Changes

- ...

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [ ] Readme (updated or not needed)
- [ ] Tests (added, updated or not needed)

### CODE REVIEW

**Review by GabLeRoux — APPROVED** [review]
tested it, seems to work fine, nice one 👍

**Comment by webbertakken** [comment]
This didn't actually solve the problem. Closing.

**Comment by GabLeRoux** [comment]
I tried the deployed app here:
https://website-git-fix-discord-page.game-ci.vercel.app/

in a private window, and it sent me to discord.

**Comment by GabLeRoux** [comment]
Oh, that's weird, it fails when we visit it directly tho:
https://website-git-fix-discord-page.game-ci.vercel.app/discord

**Comment by webbertakken** [comment]
Hmm. Yea the direct link should work too. I will raise another PR and leave the target to serverless which is preferable because it's closer to production.

**Pull request closed without merging**
