### PR TITLE
docs: How to handle androidVersionCode and date-based versions

### PR DESCRIPTION
**Pull request by johanhelsing-attensi**
#### Changes

Add some info about how to deal with androidVersionCode if your project uses a date-based versioning scheme.

#### Checklist

- [x] Read the contribution [guide](../blob/main/CONTRIBUTING.md) and accept the [code](../blob/main/CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Comment by webbertakken** [comment]
Thanks for your contribution.

In this case I do not think it's wise to defer from the versioning scheme as you suggest.

- GameCI and contributors carefully considered versioning schemes. In our automatic versioning as well, which can generate a version based on a tag like `v2021.3`.
- The android store team has undoubtably put some thought into what to make the maximum version `MAXINT (2147483647)`. A version number that will most likely be good for longer than the lifetime of any project that will ever be built by GameCI actions or the existence of Unity itself.

In that sense the version is not really "dangerously close" as it takes 125 years to reach it.

**Comment by johanhelsing-attensi** [comment]
@webbertakken the problem is that the builder action fails with an error when you get "dangerously close"

**Comment by johanhelsing-attensi** [comment]
https://github.com/game-ci/unity-builder/blob/501c67e40cf144812c33bf3e883864938410510a/src/model/android-versioning.ts#L26

**Comment by webbertakken** [comment]
I see. The error should probably be thrown above `2050_000_000`.

**Pull request closed without merging**
