### PR TITLE
chore: #324 Fix type check of staged files

### PR DESCRIPTION
**Pull request by timagixe**
#### Changes

- Closes https://github.com/game-ci/documentation/issues/324
- Move `--skipLibCheck` CLI flag to `tsconfig.json`
- Run `typecheck` script on pre-commit instead of `tsc` with custom compilerOption flags

#### Checklist

- [x] Read the contribution [guide](../blob/main/CONTRIBUTING.md) and accept the
      [code](../blob/main/CODE_OF_CONDUCT.md) of conduct
- [ ] Readme - **not needed**
- [ ] Tests - **not needed**

### CODE REVIEW

**Review by webbertakken — COMMENTED** [review]
This will check all files instead of only staged files.

Ideally precommit checks are blazing fast.

How long does the typecheck take for all files? This change is in the right direction, however, if it takes longer than a second or two we should probably create a follow-up to make it process staged files only.

**Review by webbertakken — APPROVED** [review]

**Comment by timagixe** [comment]
@webbertakken 

It takes 7.56s for me to complete full project `typecheck`.

```
% yarn typecheck                
yarn run v1.22.19
$ tsc
✨  Done in 7.49s.
```

We can consider using this small wrapper ([tsc-files](https://www.npmjs.com/package/tsc-files)) around `tsc` that helps run `tsc` on staged files without ignoring `tsconfig.json`. Let me know what do you think of it.

**Comment by webbertakken** [comment]
@timagixe I think that would be the most elegant solution indeed, short of removing the whole hook entirely.

If you're able to get that to work with lefthook that would be amazing.

If `lefthook` is causing trouble somehow, know that I'm also planning to move our repos back to `lint-staged` and `husky` since their cross platform support now properly [works](https://github.com/okonet/lint-staged/issues/1145) again.

**Comment by timagixe** [comment]
@webbertakken I have set up `tsc-files`, please take a look when you have a chance.

**Review by webbertakken — APPROVED** [review]

**Comment by webbertakken** [comment]
Thank you very much @timagixe

**Comment by timagixe** [comment]
My pleasure @webbertakken  🙌

**Pull request merged**
