### PR TITLE
Update 03-test-runner.mdx

### PR DESCRIPTION
**Pull request by xeontem**
Important step for uploading test results.
without this step action throws an "Integration" error.

#### Changes

- ...

#### Checklist

- [x] Read the contribution [guide](../blob/main/CONTRIBUTING.md) and accept the
      [code](../blob/main/CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Review by webbertakken — APPROVED** [review]
LGTM. @davidmfinol wanna have another look?

**Comment by davidmfinol** [comment]
Can we move this paragraph to an earlier location on this page? 
I think it makes more sense to move it to line 161, to move it closer to the description of the `githubToken`.

**Comment by xeontem** [comment]
I tested `upload-artifact` flow only. Cannot tell if it is actual for `githubToken`

Sure, moved it to line 161.

**Review by davidmfinol — APPROVED** [review]

**Review by GabLeRoux — APPROVED** [review]

**Comment by GabLeRoux** [comment]
I fixed code formatting, transformed requirements into a list. Thanks for the contributions! 🎉

**Pull request merged**
