### PR TITLE
Add the need for custom .gitignore extensions to the Getting Started guide. (#365)

### PR DESCRIPTION
**Pull request by kemmel-dev**
#### Changes

This is a proposal to alter the `getting started` section and `common issues` to reflect that you need to add the temporary files created by the runners to your `.gitignore` to prevent their branch from becoming dirty.
It would resolve issue  #365 

- I expanded the `.gitignore` section in `01-getting-started.mdx`
- I extended the `dirty branch` common issue text to refer back to the section mentioned above.

#### Checklist

- [ x ] Read the contribution [guide](../blob/main/CONTRIBUTING.md) and accept the
      [code](../blob/main/CODE_OF_CONDUCT.md) of conduct
- [ x ] Readme (updated or not needed)
- [ x ] Tests (added, updated or not needed)

### CODE REVIEW

**Review by webbertakken — APPROVED** [review]
LGTM

**Comment by kemmel-dev** [comment]
Failed due to missing prettier requirements. I guess I only ran it for the index file...
I ran prettier again and committed the change.

**Comment by webbertakken** [comment]
> Failed due to missing prettier requirements. I guess I only ran it for the index file... 

You can solve this problem by following the [CONTRIBUTING.md #plugins](https://github.com/game-ci/documentation/blob/main/CONTRIBUTING.md#plugins) where it explains how to auto run prettier in a range of several IDEs.

**Comment by kemmel-dev** [comment]
Oof, I just noticed that the link on `index.mdx` that links to the Common Troubleshooting page for branch is dirty links to

`https://game.ci/docs/troubleshooting/common-issues#branch-is-dirty]`

instead of

`https://game.ci/docs/troubleshooting/common-issues#branch-is-dirty`

breaking the link.

Do I open another PR?

**Comment by webbertakken** [comment]
No problem!

If you'd like to fix it indeed, simply open another PR. 

Make sure to create a new branch based on on the lastest `main` branch to prevent conflicts in the new PR.

**Pull request merged**
