### PR TITLE
Update androidSymbolType default value

### PR DESCRIPTION
**Pull request by davidmfinol**
#### Changes

- Update androidSymbolType default value

#### Checklist

- [x] Read the contribution [guide](../blob/main/CONTRIBUTING.md) and accept the
      [code](../blob/main/CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Comment by GabLeRoux** [comment]
Relates to https://github.com/game-ci/unity-builder/pull/510

**Review by GabLeRoux — APPROVED** [review]

**Comment by davidmfinol** [comment]
@GabLeRoux @AndrewKahr My understanding is that this will make the android symbols be generated by default, where before they were not generated. I don't foresee this breaking anyone's pipelines, but maybe it would be better to keep the default value as 'none' to be on the safer side?

**Comment by AndrewKahr** [comment]
@davidmfinol @GabLeRoux My thinking is in most cases you are gonna want symbols for play console etc to symbolicate crashes. But if there is a concern this shouldn't be the default behavior we can always go back to none.

**Comment by davidmfinol** [comment]
It's probably better to be more cautious and wait to change the default until `v3`.
@AndrewKahr Can you raise a PR to unity builder to reset the default to none?

**Pull request closed without merging**
