### PR TITLE
Improve AppStore/GooglePlay deployment guides

### PR DESCRIPTION
**Pull request by uchar**
#### Changes

- Automate `Missing Compliance` error in TestFlight
- Change step number in `5- Add secrets to your Github repo` to 2
- Sync deployment guide in v1 and v2

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Review by webbertakken — APPROVED** [review]

**Review by davidmfinol — APPROVED** [review]

**Comment by webbertakken** [comment]
Looking at this again, I don't think we should be "syncing v1 with v2". There are people who used the previous revision of the docs and should not be updated. The other changes look fine.

**Comment by webbertakken** [comment]
@uchar I'll merge this after you revert v1 files.

**Comment by uchar** [comment]
@webbertakken done

**Comment by webbertakken** [comment]
Thank you very much @uchar!

**Pull request merged**
