### PR TITLE
Update GitHub docs to v2

### PR DESCRIPTION
**Pull request by davidmfinol**
#### Changes

- Update GitHub docs to v2

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Comment by webbertakken** [comment]
We should consider recommending locked versions like `v2.0` and `v2-alpha-6` as I would consider rolling versions for CI workflows bad practice. Especially for bigger teams where you don't want complex flows to break unexpectedly.

From a maintainers perspective this also puts less pressure on us to never have any breaks.

**Comment by davidmfinol** [comment]
Using a simple `v2` is what GitHub recommends for their official actions (see [the quick-start](https://docs.github.com/en/actions/quickstart) and even [the repo for the checkout action](https://github.com/actions/checkout).

I like how clean this looks, and how it opens up the possibility to have bugs and security issues be fixed without requiring users to do anything. 
I haven't been able to find any details from the GitHub team that explains how or why they use `v2` in their documentation instead of a fixed version, but I think it would good to try to find this.

**Comment by davidmfinol** [comment]
I found this: https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#versioning

**Comment by webbertakken** [comment]
> I found this: https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#versioning

Yea, so looks like they recommend simple versions like v1 and v2 by default, which makes sense in general.

However I think we fall into the advanced case of needing a bit of certainty that we do not break peoples CI workflows too often and give people that need maximum stability the chance to use pinned versions.

Their recommendation (if using v0, v1, etc for major) is to make the major digit a rolling tag; Their suggested approach:

```
git tag -fa v1 -m "Update v1 tag"
git push origin v1 --force
```

To me it's fine to do that, as long as we have a light weight way to do it. Perhaps automatically after every release.

**Comment by davidmfinol** [comment]
>Perhaps automatically after every release.

Funnily enough, we could use a GitHub Action to do this: https://github.com/marketplace/actions/actions-tagger

We would want to be extra careful whenever we create a new release, but even if we do accidently introduce a breaking change, we could always roll-back the tag to the previous release.

**Comment by webbertakken** [comment]
Sounds like a plan :) That way we don't forget to roll the major tag.

**Pull request merged**
