### PR TITLE
Add feature of copy button to copy to clipboard

### PR DESCRIPTION
**Pull request by Waryserpant122**
#### Changes

- Added copy button to copy the code snippet to the clipboard.

#### Checklist

- [ x] Read the contribution [guide](../blob/main/CONTRIBUTING.md) and accept the [code](../blob/main/CODE_OF_CONDUCT.md) of conduct
- [ x] Readme (updated or not needed)
- [x ] Tests (added, updated or not needed)

Closes https://github.com/game-ci/documentation/issues/204#issuecomment-893231819

### CODE REVIEW

**Comment by webbertakken** [comment]
Could you make it so that the button is visually inside the codeblock instead of in the wrapper?

And have you considered using `children` directly? Instead of using refs  to the UI component?

**Comment by webbertakken** [comment]
Closes https://github.com/game-ci/documentation/issues/204#issuecomment-893231819

**Comment by webbertakken** [comment]
Also note that you can use `useNotification` instead of showing the "code was copied to clipboard" inline, which might be good if you want to copy the same block multiple times (as the button wouldn't disappear).

**Comment by Waryserpant122** [comment]
Hi, Yes I took your advice and have done some changed. We can also discuss how we can make it look better

**Comment by webbertakken** [comment]
Great changes, this second iteration looks much cleaner.

Thank you for your contributions!

**Comment by Waryserpant122** [comment]
Any more things to do/add?

**Comment by webbertakken** [comment]
You made it into a very usable state, so I'd say it's good enough. 

Of course there are always things to improve further. I suppose the code blocks could be further improved if you are ready for more :)

- After upgrading to the latest react-markdown, the wrapper from the code blocks is 100% wide instead of the specific amount of pixels. The desired behaviour is 
- The background colour of the wrapper should also match the background of the code blocks.
- The copy button should use `position: absolute` so that it overlays the code block instead of pushing the code itself down.

image

**Comment by Waryserpant122** [comment]
Made some changes. You can check PR #208

**Pull request merged**
