### PR TITLE
WIP: Added oembed plugin and test youtube video.

### PR DESCRIPTION
**Pull request by yanniboi**
#### Changes

- Allow html in markup with limited parsing so we can render youtube embeds.

#### Checklist

- [x] Read the contribution [guide](../blob/main/CONTRIBUTING.md) and accept the [code](../blob/main/CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Comment by yanniboi** [comment]
Having trouble with the `yarn build` locally so creating a test build here to check something.

**Comment by webbertakken** [comment]
Is it because `plugins` prop should be `remarkPlugins`?

**Comment by yanniboi** [comment]
In version 6 of react-markdown yes but game-ci is using v5. Any idea what might be causing this on `yarn build`

```
./node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/var/www/html/node_modules/node-fetch/lib'


> Build error occurred
/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:1
TypeError: (0 , _styleChecker.canUseDocElement) is not a function
    at Object.sVM9 (/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:311597:40)
    at __webpack_require__ (/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:31:31)
    at Object.CC+v (/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:66495:38)
    at __webpack_require__ (/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:31:31)
    at Object.bmkC (/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:195929:37)
    at __webpack_require__ (/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:31:31)
    at Object.C7EO (/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:65477:11)
    at __webpack_require__ (/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:31:31)
    at Module.1uJF (/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:26269:26)
    at __webpack_require__ (/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:31:31) {
  type: 'TypeError'
}
error Command failed with exit code 1.


```

I'm getting this error without having made any changes...

**Comment by yanniboi** [comment]
Oh, I'm using the wrong remark-oembed repo. That's something I can try tomorrow.

**Comment by webbertakken** [comment]
Yea so 

> Build error occurred
/var/www/html/.next/serverless/pages/docs/[...documentation-page].js:1

means that it's during the building of the static pages. all docs are parsed as static pages on build time.

It must have something to do with the plugin configuration indeed. Maybe we need to just upgrade react-markdown or use the right repo as you mentioned.

**Comment by webbertakken** [comment]
I quickly did the upgrade to the latest major version react-markdown, so that's out of the way.

See https://github.com/game-ci/documentation/pull/193

**Comment by yanniboi** [comment]
I've had a look at your updates to `react-markdown` and they dont appear to make using the `remark-oembed` plugin any easier.

Here is my proposed resolution:

 - Allow html in markdown.
 - Disallow any script tags.
 - Strip out anything that isn't an iframe.
 - Strip out any iframes that don't use youtube as the source (apologies for the rubbish regex... not my strength).

**Comment by yanniboi** [comment]
I've also added #194 as that is a fix to the issue I was having with `yarn build`.

**Comment by yanniboi** [comment]
Rebased to work with #193.

New approach needed. I am using the `rehype-raw` plugin to reparse the whole document tree, which will allow html in the markdown.

There is now no filtering or sanitizing of markup (this could be handled with https://github.com/rehypejs/rehype-sanitize).

**Comment by webbertakken** [comment]
> I've had a look at your updates to `react-markdown` and they dont appear to make using the `remark-oembed` plugin any easier.
> 
> Here is my proposed resolution:
> 
> * Allow html in markdown.
> * Disallow any script tags.
> * Strip out anything that isn't an iframe.
> * Strip out any iframes that don't use youtube as the source (apologies for the rubbish regex... not my strength).

Should we create a bugreport with that plugin? Sounds like it doesn't work correctly?

**Comment by yanniboi** [comment]
Yea so I'm not entirely sure where. `react-markdown` mentions the plugin in its list of supported plugins. The plugin itself makes no mention how to use it with react, so I would say that maybe it's and integration issue? 

Ideally I would like to dig deeper into the code and find out where r-m actually executes the plugins... So far ive just been able to find where it merges all the plugin types together and stores them...

**Comment by yanniboi** [comment]
I might need to take a closer look at the actual render pipeline...

https://github.com/remarkjs/react-markdown#architecture

**Comment by webbertakken** [comment]
> Yea so I'm not entirely sure where. `react-markdown` mentions the plugin in its list of supported plugins. The plugin itself makes no mention how to use it with react, so I would say that maybe it's and integration issue?
> 
> Ideally I would like to dig deeper into the code and find out where r-m actually executes the plugins... So far ive just been able to find where it merges all the plugin types together and stores them...

I found the plugin under [props](https://github.com/remarkjs/react-markdown#props), under remark plugins

image

Which shows an entire [list of plugins](https://github.com/remarkjs/remark/blob/main/doc/plugins.md#list-of-plugins).

**Comment by yanniboi** [comment]
> Which shows an entire list of plugins.
Yes thats what I meant by "list of supported plugins".

I was purely making the point that I'm not 100% sure I'm using it wrong or if its broken. Based on all the documentation I can find I think I'm doing it right, but that doesnt mean I'm not missing something.

Also there are two oembed plugins. One standard and one for loading the embeds asynchronously.

Ive tried both. The standard one runs with not errors but doesnt seem to do anything. The asynchronous one errors because something with the async structure doesnt work.. But Ive not debugged that enough to know where it goes wrong.

**Comment by webbertakken** [comment]
I tried both plugins and didn't get them to work either.

What about something like this? https://github.com/game-ci/documentation/pull/195/files

**Comment by webbertakken** [comment]
As we both liked using a component over badly maintained plugins better (see previous comment), I think we can close this.

Thanks for the effort of trying to make that work by the way.

**Pull request closed without merging**
