### PR TITLE
feat: introduce v3

### PR DESCRIPTION
**Pull request by webbertakken**
#### Changes

- Introduce v3

Also had to do a few other things to make it run smoothly

- Upgrade TS and eslint resolver for TS
- Upgrade Docusaurus to latest
- Upgrade a few more packages
- Update icon imports
- Pin yarn and node version using Volta

#### Checklist

- [x] Read the contribution [guide](../blob/main/CONTRIBUTING.md) and accept the
      [code](../blob/main/CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Comment by EliasVal** [comment]
Looking into the `Type check` CI, maybe [this](https://github.com/facebook/docusaurus/pull/9050) should be able to fix the issue :)

**Comment by webbertakken** [comment]
> Looking into the `Type check` CI, maybe [this](https://github.com/facebook/docusaurus/pull/9050) should be able to fix the issue :)

Thanks @EliasVal!

**Review by davidmfinol — APPROVED** [review]
LGTM

**Review by GabLeRoux — APPROVED** [review]

**Comment by GabLeRoux** [comment]
Amazing work! 🎉

**Comment by GabLeRoux** [comment]
I think this is currently blocked by the publication of v3 for `unity-builder`:
https://github.com/game-ci/unity-builder/releases

Will we also need to bump `unity-test-runner`?

**Comment by webbertakken** [comment]
> I think this is currently blocked by the publication of v3 for `unity-builder`: https://github.com/game-ci/unity-builder/releases
> 
> Will we also need to bump `unity-test-runner`?

Probably a good idea yea. We'll have to bump to 4 for the CLI integration anyway.

**Pull request merged**
