### PR TITLE
Docs/diagrams

### PR DESCRIPTION
**Pull request by cloudymax**
#### Changes

- adds some cosmetic diagrams made in draw.io/diagrams.net

### CODE REVIEW

**Review by webbertakken — APPROVED** [review]

**Comment by webbertakken** [comment]
Looks great! Thanks.

**Comment by GabLeRoux** [comment]
For this one, I see some logos at the top have incorrect scale:



Could be nice to have access to diagrams source so we can build around it as well.

Thanks a lot for taking the time to create these btw. I've only pointed some small details, but these additions will definitely make it easier understand what's going on :D

**Comment by cloudymax** [comment]
> So far, these aren't embed anywhere on the site, but they sure are handy.
> 
> I suggest we rewrite this one as a web based table with links to sources of the pricing and a note stating that numbers may change over time, maybe with something like a _last updated at_:
> 
> 
> 
> I would also recommend aligning the floating numbers for easier eye comparison and specifying currency.

I'm in full agreement, I also want to better explain circle cis price formula since it's really unintuitive. Thanks for the feedback 🙏

**Comment by cloudymax** [comment]
> For this one, I see some logos at the top have incorrect scale:
> 
> 
> 
> Could be nice to have access to diagrams source so we can build around it as well.
> 
> Thanks a lot for taking the time to create these btw. I've only pointed some small details, but these additions will definitely make it easier understand what's going on :D

Good eye on the logos! I'll go in and do a quality pass shortly 

As for the file formats, unless I'm mistaken (and I often am) the .drawio.svg files should contain the full diagram and be editable in draw.io/diagrams.net and VScode(with the addon for draw.io). If that's not the case or it's simply preferred to have both file formats on hand I'm happy to accomodate 🙌

**Comment by GabLeRoux** [comment]
> As for the file formats, unless I'm mistaken (and I often am) the .drawio.svg files should contain the full diagram and be editable in [draw.io](https://draw.io/)/[diagrams.net](https://diagrams.net/) and VScode([with the addon for draw.io](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio)). If that's not the case or it's simply preferred to have both file formats on hand I'm happy to accomodate 🙌

Oh nice, I confirm it works. I just opened the files in [draw.io](https://draw.io/) successfully. I didn't notice the `draw.io` in the file names. Also I just learned about that editable svg format feature and the extension, thanks for sharing :tada:

**Comment by webbertakken** [comment]
I am also very happy to have found out about that plugin! I'm using diagrams.net a whole lot.

> It supports diagram files with the extensions .drawio.(svg|png|xml) and .dio.(svg|png|xml).

We should probably also add that plugin to our CONTRIBUTING.md under the plugins section: https://github.com/game-ci/documentation/blob/main/CONTRIBUTING.md#plugins

**Pull request merged**
