### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by webbertakken**
#### Changes

- Create initial home page
- Fix race condition setting name of an object
- Make logo background transparent
- Simplify global styles
- Make NavBar sticky on home page
- Install classnames

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [ ] Readme (updated or not needed)
- [ ] Tests (added, updated or not needed)

### CODE REVIEW

**Comment by webbertakken** [comment]
#### 📝Changed routes:


| [**…...documentation-page\]**](https://website-aqr3flcwc-game-ci.vercel.app/docs/[...documentation-page]) | [**/docs/docker/versions**](https://website-aqr3flcwc-game-ci.vercel.app/docs/docker/versions) |
|:-:|:-:|
|<a href="https://website-aqr3flcwc-game-ci.vercel.app/docs/[...documentation-page]">Screenshot of /docs/[...documentation-page]</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/q8vfiswaU-QfMNZrDXdnUseTHR8n9t1_1EB04P6Jw-t2RnlEZVnbR4zV7-r3KAfgt3XAHmfZTtX03TUnR8j0Gw.png">(view full size)</a> |<a href="https://website-aqr3flcwc-game-ci.vercel.app/docs/docker/versions">Screenshot of /docs/docker/versions</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/sXInw9NKcr_xmmXXX7m3bDNQKG7qvmQFyb-8iK0Zj6bAOgXIPT6n9fVWqpNCvotMzMPSe4uIRtPbz7EG2SXc-g.png">(view full size)</a> |



| [**/docs**](https://website-aqr3flcwc-game-ci.vercel.app/docs) | [**/example**](https://website-aqr3flcwc-game-ci.vercel.app/example) |
|:-:|:-:|
|<a href="https://website-aqr3flcwc-game-ci.vercel.app/docs">Screenshot of /docs</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/yq-hXCxewTiXWRw9Amo9TuqwIytACHiPxXD4K6bPG5QBKS6SXcjQT3kkEHB23uczQIu6xL8alUxg0eCIc3Njvw.png">(view full size)</a> |<a href="https://website-aqr3flcwc-game-ci.vercel.app/example">Screenshot of /example</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/_jl1aWfCmMRGRGoUmeCYWByEJkYJVucU8vP0dRzouK0eIzKORUb_3iujSYvLaW3-W6ZBscC1CuGhcHKV-NTDXA.png">(view full size)</a> |



| [**/**](https://website-aqr3flcwc-game-ci.vercel.app/) |
|:-:|
|<a href="https://website-aqr3flcwc-game-ci.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://iad.microlink.io/Scx-zYp3uFmwTKH-cZuUvRwENHOnudcUQ1bfJQuXkCOtCMtNyaxneriE2zMrdzG2mr16jhMtD4-7KWCW4uY5cg.png">(view full size)</a> |







Commit 4a763dde600b67e91c93eebaa31d72d71f655e10 (https://website-aqr3flcwc-game-ci.vercel.app).

**Review by GabLeRoux — APPROVED** [review]

**Comment by GabLeRoux** [comment]
oh I just approved on commit actually, anyway, I did the same for ruby ahah. I went trough all docs pages and we don't have any other languages for now 👍

**Comment by webbertakken** [comment]
Cool. I'll merge this one then.

**Comment by webbertakken** [comment]
by the way for `console` I usually use `bash` instead.

**Comment by GabLeRoux** [comment]
Actually, console should be `plaintext` as we should not try to figure out bash commands out of text result from commands output. See #164 I'll see if there's a difference with no `console` vs `plaintext`.

**Pull request merged**
